### PR TITLE
fix: add `expiresIn` parameters in getSignedUrl method

### LINKED ISSUE #5: S3 Signed URL Expiration
Following https://docs.adonisjs.com/guides/drive#getsignedurl to generate a pre-signed URL from S3 using the snippet below

```
const url = await Drive.getSignedUrl(
    file_location,
    {
      contentType: 'application/pdf',
      expiresIn: 120,
    }
)
```

yields an URL like this
```
https://redacted_s3_url?
        X-Amz-Algorithm=AWS4-HMAC-SHA256&
        X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&
        X-Amz-Credential=redacted_credential&
        X-Amz-Date=20220302T210925Z&
        X-Amz-Expires=900&
        X-Amz-Signature=redacted_signature&
        X-Amz-SignedHeaders=host&
        response-content-type=application%2Fpdf&
        x-id=GetObject
```

The issue is that `expiresIn` has no effect on the `X-Amz-Expires` header as it is always set to `900` seconds. It happens when using both string or integer values (i.e. `'2mins'` or `120`). Am I missing something or is this feature not available for S3?

---

### Configs

contracts/drive.ts
```
declare module '@ioc:Adonis/Core/Drive' {
  interface DisksList {
    s3: {
      config: S3DriverConfig
      implementation: S3DriverContract
    }
  }
}
```

config/drive.ts
```
const driveConfig: DriveConfig = {
  disk: Env.get('DRIVE_DISK'),
  disks: {
    s3: {
      driver: 's3',
      visibility: 'private',
      key: Env.get('AWS_ACCESS_KEY'),
      secret: Env.get('AWS_SECRET_KEY'),
      region: Env.get('S3_REGION'),
      bucket: Env.get('S3_BUCKET'),
      endpoint: Env.get('S3_ENDPOINT'),
    },
  },
}
```

### Dependencies
```
"@adonisjs/core": "^5.4.1",
"@adonisjs/drive-s3": "^1.0.5",
```

### Node
```
NodeJS - v14.18.3
NPM - 6.14.15
```

### PR DESCRIPTION
**Pull request by Julien-R44**
Fixes #5

### CODE REVIEW

File: src/Drivers/S3.ts [hunk 1]
```diff
@@ -259,7 +260,10 @@ export class S3Driver implements S3DriverContract {
           Key: location,
           Bucket: this.config.bucket,
           ...this.transformContentHeaders(options),
-        })
+        }),
+        {
+          expiresIn: string.toMs(options?.expiresIn || '15min') / 1000,
```
Comment (RomainLanz) [inline src/Drivers/S3.ts:265]: Instead of manually dividing by one thousand, wouldn't it be better to add a new helper in [poppinss/utils](https://github.com/poppinss/utils)?

Comment (thetutlage) [reply src/Drivers/S3.ts:265]: Yup.

Comment (thetutlage) [reply src/Drivers/S3.ts:265]: Maybe wait and see if we need it at other places as well and then extract to a reusable helper?

Comment (Julien-R44) [reply src/Drivers/S3.ts:265]: I don't really have an opinion on this. Tell me what you guys prefer and I'll do it 🙂

Comment (thetutlage) [reply src/Drivers/S3.ts:265]: Let's merge it for now!
